---
abstract: 'Perl interface to durl.me'
author:
  - 'JEEN Lee <aiatejin@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.62
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Shorten-Durl
no_index:
  directory:
    - inc
    - t
requires:
  Filter::Util::Call: 0
  WWW::Shorten: 2.05
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/JEEN/p5-WWW-Shorten-Durl.git
version: 0.05
